### ISSUE TITLE
[ANCHORE] Unsolicited random wisdom of the moment

### ISSUE THREAD

**Issue by dakaneye** [dakaneye/anchore-engine#1]
```
details:
  msg: Never pick a fight with people who buy ink by the barrel - Mark Twain
id: 021e56368a6e4b938e01e2b891072ae7
level: info
message: Unsolicited random wisdom of the moment
resource:
  id: null
  type: wisdom
  user_id: admin
source:
  base_url: http://notifications:8228
  hostid: anchore-quickstart
  request_id: null
  servicename: notifications
timestamp: '2020-11-07T00:16:01.901592'
type: system.test.random_wisdom
```
